# Generated by Django 4.1.13 on 2024-06-02 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('skybnb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('dormitorios', models.IntegerField()),
                ('banos', models.IntegerField()),
                ('huespedes', models.IntegerField()),
                ('mascotas', models.BooleanField()),
                ('precio', models.IntegerField()),
                ('estado_destacado', models.BooleanField()),
                ('actividades', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='skybnb.actividades')),
                ('servicios', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='skybnb.servicios')),
                ('tipoalojamiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tipo', to='skybnb.tipoalojamiento')),
                ('ubicacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='skybnb.ubicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
