# Generated by Django 4.1.13 on 2024-06-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skybnb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenalojamiento',
            name='image10',
            field=models.TextField(default='default_value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenalojamiento',
            name='image11',
            field=models.TextField(default='default_value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenalojamiento',
            name='image12',
            field=models.TextField(default='default_value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenalojamiento',
            name='image6',
            field=models.TextField(default='default_value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenalojamiento',
            name='image7',
            field=models.TextField(default='default_value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenalojamiento',
            name='image8',
            field=models.TextField(default='default_value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenalojamiento',
            name='image9',
            field=models.TextField(default='default_value'),
            preserve_default=False,
        ),
    ]
