# Generated by Django 4.1.13 on 2024-06-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skybnb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
