# Generated by Django 4.1.13 on 2024-06-18 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skybnb', '0002_imagenalojamiento_image10_imagenalojamiento_image11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='tipoalojamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo', to='skybnb.tipoalojamiento'),
        ),
        migrations.AlterField(
            model_name='alojamiento',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='skybnb.ubicacion'),
        ),
        migrations.AlterField(
            model_name='imagenalojamiento',
            name='image10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagenalojamiento',
            name='image11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagenalojamiento',
            name='image12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagenalojamiento',
            name='image6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagenalojamiento',
            name='image7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagenalojamiento',
            name='image8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagenalojamiento',
            name='image9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
