# Generated by Django 4.1.13 on 2024-06-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skybnb', '0003_alter_alojamiento_tipoalojamiento_and_more'),
    ]

    operations = [
    ]
